# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in ruby_demo.gemspec
gemspec

gem "rake", "~> 13.0"
gem "aws-sdk-dynamodb", "1.86.0"
gem "aws-sdk-ssm", "1.151.0"
